package models;
// Generated 11 f�vr. 2014 21:52:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CritereBs generated by hbm2java
 */
@Entity
@Table(name="critere_bs"
    ,catalog="ihm_db"
)
public class CritereBs  implements java.io.Serializable {


     private Integer idcritaire;
     private Categorie categorie;
     private String libcritaire;
     private String definition;
     private Set<QuestionBs> questionBses = new HashSet<QuestionBs>(0);

    public CritereBs() {
    }

    public CritereBs(Categorie categorie, String libcritaire, String definition, Set<QuestionBs> questionBses) {
       this.categorie = categorie;
       this.libcritaire = libcritaire;
       this.definition = definition;
       this.questionBses = questionBses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcritaire", unique=true, nullable=false)
    public Integer getIdcritaire() {
        return this.idcritaire;
    }
    
    public void setIdcritaire(Integer idcritaire) {
        this.idcritaire = idcritaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategorie")
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

    
    @Column(name="libcritaire", length=45)
    public String getLibcritaire() {
        return this.libcritaire;
    }
    
    public void setLibcritaire(String libcritaire) {
        this.libcritaire = libcritaire;
    }

    
    @Column(name="definition", length=65535)
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="critereBs")
    public Set<QuestionBs> getQuestionBses() {
        return this.questionBses;
    }
    
    public void setQuestionBses(Set<QuestionBs> questionBses) {
        this.questionBses = questionBses;
    }


    @Override
    public String toString() {
        return  libcritaire ;
    }
  public String des(){
        return definition;
    }


}


