package models;
// Generated 11 vr. 2014 21:52:45 by Hibernate Tools 3.6.0


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lignegrille generated by hbm2java
 */
@Entity
@Table(name="lignegrille"
    ,catalog="ihm_db"
)
public class Lignegrille  implements java.io.Serializable {


     private Integer idigne;
     private Grille grille;
     private QuestionBs questionBs;
     private int reponse;
     private String justification;

    public Lignegrille() {
    }

	
    public Lignegrille(Grille grille, QuestionBs questionBs, int reponse) {
        this.grille = grille;
        this.questionBs = questionBs;
        this.reponse = reponse;
    }
    public Lignegrille(Grille grille, QuestionBs questionBs, int reponse, String justification) {
       this.grille = grille;
       this.questionBs = questionBs;
       this.reponse = reponse;
       this.justification = justification;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idigne", unique=true, nullable=false)
    public Integer getIdigne() {
        return this.idigne;
    }
    
    public void setIdigne(Integer idigne) {
        this.idigne = idigne;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idgrille", nullable=false)
    public Grille getGrille() {
        return this.grille;
    }
    
    public void setGrille(Grille grille) {
        this.grille = grille;
    }

@ManyToOne(cascade = {CascadeType.ALL}, fetch = FetchType.EAGER)
    @JoinColumn(name="idquestion", nullable=false)
    public QuestionBs getQuestionBs() {
        return this.questionBs;
    }
    
    public void setQuestionBs(QuestionBs questionBs) {
        this.questionBs = questionBs;
    }

    
    @Column(name="reponse", nullable=false)
    public int getReponse() {
        return this.reponse;
    }
    
    public void setReponse(int reponse) {
        this.reponse = reponse;
    }

    
    @Column(name="justification", length=80)
    public String getJustification() {
        return this.justification;
    }
    
    public void setJustification(String justification) {
        this.justification = justification;
    }




}


