package models;
// Generated 11 fvr. 2014 21:52:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PopulationCible generated by hbm2java
 */
@Entity
@Table(name="population_cible"
    ,catalog="ihm_db"
)
public class PopulationCible  implements java.io.Serializable {


     private Integer idpopulation;
     private String libpopulation;
     private Set<QuestionBs> questionBses = new HashSet<QuestionBs>(0);
     private Set<Grille> grilles = new HashSet<Grille>(0);

    public PopulationCible() {
    }

	
    public PopulationCible(String libpopulation) {
        this.libpopulation = libpopulation;
    }
    public PopulationCible(String libpopulation, Set<QuestionBs> questionBses, Set<Grille> grilles) {
       this.libpopulation = libpopulation;
       this.questionBses = questionBses;
       this.grilles = grilles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpopulation", unique=true, nullable=false)
    public Integer getIdpopulation() {
        return this.idpopulation;
    }
    
    public void setIdpopulation(Integer idpopulation) {
        this.idpopulation = idpopulation;
    }

    
    @Column(name="libpopulation", nullable=false, length=50)
    public String getLibpopulation() {
        return this.libpopulation;
    }
    
    public void setLibpopulation(String libpopulation) {
        this.libpopulation = libpopulation;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="question-population", catalog="ihm_db", joinColumns = { 
        @JoinColumn(name="idp", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idq", nullable=false, updatable=false) })
    public Set<QuestionBs> getQuestionBses() {
        return this.questionBses;
    }
    
    public void setQuestionBses(Set<QuestionBs> questionBses) {
        this.questionBses = questionBses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="populationCible")
    public Set<Grille> getGrilles() {
        return this.grilles;
    }
    
    public void setGrilles(Set<Grille> grilles) {
        this.grilles = grilles;
    }

  @Override
    public String toString() {
        return libpopulation ;
    }


}


