package models;
// Generated 11 fevr. 2014 21:52:45 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionNielsen generated by hbm2java
 */
@Entity
@Table(name="question_nielsen"
    ,catalog="ihm_db"
)
public class QuestionNielsen  implements java.io.Serializable {


     private Integer idquestion;
     private CritereNielsen critereNielsen;
     private String question;

    public QuestionNielsen() {
    }

    public QuestionNielsen(CritereNielsen critereNielsen, String question) {
       this.critereNielsen = critereNielsen;
       this.question = question;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idquestion", unique=true, nullable=false)
    public Integer getIdquestion() {
        return this.idquestion;
    }
    
    public void setIdquestion(Integer idquestion) {
        this.idquestion = idquestion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcritaire")
    public CritereNielsen getCritereNielsen() {
        return this.critereNielsen;
    }
    
    public void setCritereNielsen(CritereNielsen critereNielsen) {
        this.critereNielsen = critereNielsen;
    }

    
    @Column(name="question", length=65535)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }




}


