package models;
// Generated 11 fevr. 2014 21:52:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Terminal generated by hbm2java
 */
@Entity
@Table(name="terminal"
    ,catalog="ihm_db"
)
public class Terminal  implements java.io.Serializable {


     private Integer idterminal;
     private String libteriminal;
     private String resolution;
     private Set<Grille> grilles = new HashSet<Grille>(0);
     private Set<QuestionBs> questionBses = new HashSet<QuestionBs>(0);

    public Terminal() {
    }

	
    public Terminal(String libteriminal) {
        this.libteriminal = libteriminal;
    }
    public Terminal(String libteriminal, String resolution, Set<Grille> grilles, Set<QuestionBs> questionBses) {
       this.libteriminal = libteriminal;
       this.resolution = resolution;
       this.grilles = grilles;
       this.questionBses = questionBses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idterminal", unique=true, nullable=false)
    public Integer getIdterminal() {
        return this.idterminal;
    }
    
    public void setIdterminal(Integer idterminal) {
        this.idterminal = idterminal;
    }

    
    @Column(name="libteriminal", nullable=false, length=20)
    public String getLibteriminal() {
        return this.libteriminal;
    }
    
    public void setLibteriminal(String libteriminal) {
        this.libteriminal = libteriminal;
    }

    
    @Column(name="resolution", length=20)
    public String getResolution() {
        return this.resolution;
    }
    
    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terminal")
    public Set<Grille> getGrilles() {
        return this.grilles;
    }
    
    public void setGrilles(Set<Grille> grilles) {
        this.grilles = grilles;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="question-terminal", catalog="ihm_db", joinColumns = { 
        @JoinColumn(name="idt", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idq", nullable=false, updatable=false) })
    public Set<QuestionBs> getQuestionBses() {
        return this.questionBses;
    }
    
    public void setQuestionBses(Set<QuestionBs> questionBses) {
        this.questionBses = questionBses;
    }


  @Override
    public String toString() {
        return libteriminal ;
    }

}


