package models;
// Generated 11 fevr. 2014 21:52:45 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeApplication generated by hbm2java
 */
@Entity
@Table(name="type_application"
    ,catalog="ihm_db"
)
public class TypeApplication  implements java.io.Serializable {


     private Integer idtype;
     private String libtype;
     private Set<QuestionBs> questionBses = new HashSet<QuestionBs>(0);
     private Set<Grille> grilles = new HashSet<Grille>(0);

    public TypeApplication() {
    }

	
    public TypeApplication(String libtype) {
        this.libtype = libtype;
    }
    public TypeApplication(String libtype, Set<QuestionBs> questionBses, Set<Grille> grilles) {
       this.libtype = libtype;
       this.questionBses = questionBses;
       this.grilles = grilles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtype", unique=true, nullable=false)
    public Integer getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }

    
    @Column(name="libtype", nullable=false, length=50)
    public String getLibtype() {
        return this.libtype;
    }
    
    public void setLibtype(String libtype) {
        this.libtype = libtype;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="question-type", catalog="ihm_db", joinColumns = { 
        @JoinColumn(name="idt", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idq", nullable=false, updatable=false) })
    public Set<QuestionBs> getQuestionBses() {
        return this.questionBses;
    }
    
    public void setQuestionBses(Set<QuestionBs> questionBses) {
        this.questionBses = questionBses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeApplication")
    public Set<Grille> getGrilles() {
        return this.grilles;
    }
    
    public void setGrilles(Set<Grille> grilles) {
        this.grilles = grilles;
    }

    @Override
    public String toString() {
        return libtype ;
    }




}


